name: Docker_v2

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check kea version
        run: |
          update=false
          kea_old=$(cat .github/VERSION | grep kea | cut -d "=" -f2)
          kea=$(docker run alpine:latest sh -c "apk -q update && apk info kea | head -n1 | cut -d ' ' -f1")
          if [ "$kea_old" != "$kea" ]; then
             echo "Found new version of kea. Launching github action"
             update=true
             echo "update=true" >> $GITHUB_ENV
          fi
          #Store values
          if [ "$update" = true ]; then
            echo "kea=$kea" > ".github/VERSION"
            git config --global user.name 'dotsoltecti'
            git config --global user.email 'dotsoltecti@users.noreply.github.com'
            git commit -am "Update version"
            git push
            echo "Saved values to disk"
          fi

         
             

